defaults:
  - name: 쉼
    title: 힐링 오디오 서비스
    content: 쉼은 집중이나 휴식이 필요한 사람들에게 ASMR이나 클래식과 같은 오디오 컨텐츠를 제공합니다. 
    android: https://play.google.com/store/apps/details?id=co.shimm.app
    tags:
     - Node.js
     - Android
     - Retrofit2

  - name: 헤쳐모여 
    title: 운동 목표 기록 서비스
    content: 러닝, 사이클에 대한 개인의 운동 목표 설정, 기록, 공유 서비스를 제공합니다
    android: https://play.google.com/store/apps/details?id=com.prography.prography_pizza
    tags:
     - Node.js
     - Android

  - name:  DailyPicture
    title: 매일 일상의 변화 기록 
    content: 기록을 한 사진들을 일정 이상의 사진들이 기록되면, 영상으로 변환하여 변화를 한눈에 볼 수 있습니다.
    android: https://play.google.com/store/apps/details?id=org.techtown.dailypicture
    tags:
      - Android
      - Kotlin
      - Django
      - Docker

  - name: cogether
    title: 개발 관련 정보를 모아서 보여주는 서비스
    content: Cogether은 개발자들에게 필요한 컨퍼런스, 교육 및 동아리 정보를 모아서 한 눈에 볼 수 있는 서비스입니다.
    website: https://cogether.kr/
    tags:
     - Django
     - React

tagmap:
  - tag: Github
    url: http://github.com/
  - tag: AWS
    url: http://aws.amazon.com/
  - tag: PostgreSql
    url: https://www.postgresql.org/
  - tag: MySQL
    url: http://www.mysql.com
  - tag: Docker
    url: https://docs.docker.com/
  - tag: Node.js
    url: https://nodejs.org/
  - tag: Retrofit
    url: https://github.com/square/retrofit
  - tag: Django
    url: https://www.djangoproject.com/
  - tag: React
    url: https://reactjs.org/